fullnameOverride: gateway

gateway:
  replicas: 2
  secretRef: gateway-env-vars
  env:
    # Configure connection to Kafka
    KAFKA_BOOTSTRAP_SERVERS: franz-kafka.conduktor.svc.cluster.local:9092
    KAFKA_SASL_MECHANISM: PLAIN
    KAFKA_SECURITY_PROTOCOL: SASL_SSL
    KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/gateway/tls/truststore/kafka.truststore.jks
    # Configure Client -> Gateway
    GATEWAY_SECURITY_PROTOCOL: DELEGATED_SASL_SSL
    GATEWAY_ADVERTISED_HOST: gateway-internal.conduktor.svc.cluster.local
    GATEWAY_ROUTING_MECHANISM: host
    GATEWAY_ADVERTISED_SNI_PORT: "9092"
    GATEWAY_FEATURE_FLAGS_INTERNAL_LOAD_BALANCING: "false"
    # # Enhanced logging
    # LOG4J2_ORG_APACHE_KAFKA_LEVEL: debug
  portRange:
    start: 9092
    count: 1
  volumes:
    - name: truststore
      secret:
        secretName: gateway-cert
        items:
        - key: kafka.truststore.jks
          path: kafka.truststore.jks
  volumeMounts:
    - name: truststore
      mountPath: /etc/gateway/tls/truststore/
      readonly: true


tls:
  enable: true
  secretRef: gateway-cert
  keystoreFile: gateway.keystore.jks
  keystoreKey: gateway.keystore.jks