gateway:
  replicas: 2
  secretRef: gateway-env-vars
  env:
    # Configure connection to Kafka
    KAFKA_BOOTSTRAP_SERVERS: kafka.conduktor.svc.cluster.local
    KAFKA_SASL_MECHANISM: PLAIN
    KAFKA_SECURITY_PROTOCOL: SASL_SSL
    # Configure Client -> Gateway
    GATEWAY_SECURITY_PROTOCOL: DELEGATED_SASL_SSL
    GATEWAY_ADVERTISED_HOST: gateway.conduktor.svc.cluster.local
    GATEWAY_ROUTING_MECHANISM: host
  portRange:
    start: 9092
    count: 1

tls:
  enable: true
  secretRef: gateway-cert