# helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka

replicaCount: 3

listeners:
  client:
    protocol: SASL_SSL
  interbroker:
    protocol: SASL_SSL
  controller:
    protocol: SASL_SSL

sasl:
  enabledMechanisms: PLAIN
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  interbroker:
    user: admin
  controller:
    user: admin
  client:
    users:
      - admin
  existingSecret: "client-passwords"


tls:
  type: jks
  sslClientAuth: "none"
  existingSecret: "kafka-cert"
  passwordsSecret: "keystore-passwords"

extraEnvVars:
  - name: KAFKA_OPTS
    value: "-Djavax.net.debug=ssl,sasl"
